default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: messenger_platform_demo_dev

test:
  <<: *default
  database: messenger_platform_demo_test
